### ISSUE TITLE
fail to mv to the mounted directory in ubuntu18.04

### ISSUE THREAD

**Issue by yr-wang-hit** [cyverse/irodsfs#12]
After successfully mounting some irods collection to my local filesystem path /mnt/irods, I tried to move some files to that mounted path and it reports error like :
``  mv: cannot create regular file '/mnt/irods/irodsfs_amd64_linux_v0.5.4.tar': Remote I/O error ``
and the rodsLog said something like:
`` Mar 13 22:13:38 pid:18449 remote addresses: 127.0.0.1, someIP ERROR: [rsDataObjOpen_impl:907] - [HIERARCHY_ERROR: no valid resource found for data object
] [error_code=[-1803000], path=[/zone1/home/rods/irodsfs_amd64_linux_v0.5.4.tar], hierarchy=[] ``

It seems that irods cannot choose the default resource to put/register the data in, But I can put the data successfully via `` iput ``. What's the situation and how to fix it? Thanks a lot.

**Comment by iychoi** [comment]
It looks like you have multiple resource servers and iRODS server cannot determine default resource for some reasons.

It also looks like other clients (python-irods-client) have default resource server configuration. I'll add a new configuration parameter in iRODS FUSE Lite in the future.

**Comment by iychoi** [comment]
@yr-wang-hit did you use `-R` parameter to specify `resource` when you did it with `iput`?

**Comment by iychoi** [comment]
Can you please try the commit 79ece76ed7be40b3a0810c277b4ef47cf6e6e8b7?

**Comment by peggy0135** [comment]
I also faced this problem.
using icommand, I can "iput -R resc1 testfile"
but I cannot use "mv testfile irodsfs_mount"

**Comment by iychoi** [comment]
Hi @peggy0135 ,

The issue occurs because your iRODS system does not have default resource server set. The patch I mentioned above adds a new command-line flag `-resource` to set a resource server to use. The flag must be given when you mount.

Would you try it with the flag once again?

**Comment by peggy0135** [comment]
"./bin/irodsfs -resource resc1 irods://rods@10.106.35.110:1247/tempZone/home/rods /root/irodsfs_mount"?
not working, or I need to rebuild the repo from the main branch?

**Comment by peggy0135** [comment]
sorry, reply late.
it worked fine after a few seconds. 
ps: it worked with the flag (-resource)
Than you

**Comment by iychoi** [comment]
@peggy0135 Nice to hear that it worked. Thanks for testing.
