### ISSUE TITLE
Transport endpoint is not connected

### ISSUE THREAD

**Issue by peggy0135** [cyverse/irodsfs#13]
I faced this problem, and confused.
step:
1. create directory (the mount point)
2. mount the file system
3. list the mount point 
4. got the error message
    ls: cannot access '/work/JC/': Transport endpoint is not connected
how I figure out : just umount and re-mount the mount point.
But I am curious, how to avoid this happened. I faced the problem every time when I do some actions with the files in the dir.
Thank you.

PS: I dump and grep some error log
      time="2022-04-12 21:37:06.230804" level=info msg="2022/04/12 21:37:06 mount helper error: fusermount: user has no write access to mountpoint /work/JC" function=parentRun package=main
time="2022-04-12 21:37:06.231039" level=error msg="failed to start background process" function=parentRun package=main
time="2022-04-12 21:37:06.231102" level=error msg="failed to run the foreground process" error="failed to start background process" function=parentMain package=main
time="2022-04-12 21:37:06.230898" level=error msg="failed to connect to FUSE" error="fusermount: exit status 1" function=ConnectToFuse package=irodsfs struct=IRODSFS
time="2022-04-12 21:37:06.230965" level=error msg="failed to connect to FUSE, terminating iRODS FUSE Lite" error="fusermount: exit status 1" function=run package=main
time="2022-04-12 21:37:06.233375" level=error msg="failed to run iRODS FUSE Lite" error="fusermount: exit status 1" function=childMain package=main
time="2022-04-12 21:39:13.805007" level=info msg="2022/04/12 21:39:13 mount helper error: fusermount: user has no write access to mountpoint /work/JC" function=parentRun package=main
time="2022-04-12 21:39:13.805203" level=error msg="failed to start background process" function=parentRun package=main
time="2022-04-12 21:39:13.805267" level=error msg="failed to run the foreground process" error="failed to start background process" function=parentMain package=main
time="2022-04-12 21:39:13.805080" level=error msg="failed to connect to FUSE" error="fusermount: exit status 1" function=ConnectToFuse package=irodsfs struct=IRODSFS
time="2022-04-12 21:39:13.805147" level=error msg="failed to connect to FUSE, terminating iRODS FUSE Lite" error="fusermount: exit status 1" function=run package=main
time="2022-04-12 21:39:13.807786" level=error msg="failed to run iRODS FUSE Lite" error="fusermount: exit status 1" function=childMain package=main
time="2022-04-12 21:41:18.692908" level=debug msg="failed to find a file - /tempZone/home/JC/testMakefile" error="could not find a data object or a directory" function=Lookup package=irodsfs struct=Dir
time="2022-04-12 21:41:18.693224" level=debug msg="failed to find a file - /tempZone/home/JC/testMakefile" error="could not find a data object or a directory" function=Lookup package=irodsfs struct=Dir
time="2022-04-12 21:41:18.693471" level=debug msg="failed to find a file - /tempZone/home/JC/testMakefile" error="could not find a data object or a directory" function=Lookup package=irodsfs struct=Dir
time="2022-04-12 21:41:18.918889" level=error msg="stacktrace from panic: goroutine 112 [running]:\nruntime/debug.Stack(0xc00046b298, 0xb2e120, 0x10b9ba0)\n\t/usr/lib/golang/src/runtime/debug/stack.go:24 +0x9f\ngithub.com/cyverse/irodsfs-common/utils.StackTraceFromPanic(0xc0001668c0)\n\t/root/go/pkg/mod/github.com/cyverse/irodsfs-common@v0.0.0-20220331024442-a069a86ca154/utils/trace.go:11 +0x5b\npanic(0xb2e120, 0x10b9ba0)\n\t/usr/lib/golang/src/runtime/panic.go:971 +0x499\ngithub.com/cyverse/irodsfs/irodsfs.(*FileHandle).Release(0xc0001be2d0, 0xcf59f8, 0xc000173940, 0xc0001be3c0, 0x0, 0x0)\n\t/root/irodsfs/irodsfs/filehandle.go:266 +0x48d\nbazil.org/fuse/fs.(*Server).handleRequest(0xc0004b4000, 0xcf59f8, 0xc000173940, 0xce80e0, 0xc000305a80, 0xc000305b00, 0xcf3d20, 0xc0001be3c0, 0xc00046bed8, 0x0, ...)\n\t/root/go/pkg/mod/bazil.org/fuse@v0.0.0-20200524192727-fb710f7dfd05/fs/serve.go:1470 +0x2a18\nbazil.org/fuse/fs.(*Server).serve(0xc0004b4000, 0xcf3d20, 0xc0001be3c0)\n\t/root/go/pkg/mod/bazil.org/fuse@v0.0.0-20200524192727-fb710f7dfd05/fs/serve.go:1015 +0x390\nbazil.org/fuse/fs.(*Server).Serve.func1(0xc0004b4000, 0xcf3d20, 0xc0001be3c0)\n\t/root/go/pkg/mod/bazil.org/fuse@v0.0.0-20200524192727-fb710f7dfd05/fs/serve.go:512 +0x6f\ncreated by bazil.org/fuse/fs.(*Server).Serve\n\t/root/go/pkg/mod/bazil.org/fuse@v0.0.0-20200524192727-fb710f7dfd05/fs/serve.go:510 +0x354\n" function=Release package=irodsfs struct=FileHandle
time="2022-04-12 21:41:18.918998" level=panic msg="runtime error: invalid memory address or nil pointer dereference" function=Release package=irodsfs struct=FileHandle

thank you.

**Comment by iychoi** [comment]
Hi @peggy0135, 
It seems that you don't have a write permission to "/work/JC" that is a mount point. Can you double check if the directory has the write permission? I'll add a quick permission check routine to prevent crash.

Thanks, 
Illyoung Choi

**Comment by peggy0135** [comment]
I am sure that I got the write permission,
because after a few moment, I can see the file with right size in the folder(mount point)
thank you
