### ISSUE TITLE
How to specify resource when using irodsfs

### ISSUE THREAD

**Issue by Narushima2030** [cyverse/irodsfs#27]
In irodsfs, from my understanding, when I add a file to a mounted collection, the resource is specified as default (demoResc).
Is it possible to specify an arbitrary resource, like the -R option of the iput command?

**Comment by iychoi** [comment]
You can specify resource server in two ways.
1. specify the resource server with a flag "--resource" when you run the irodsfs.
2. specify the resource server in the "resource" field in the YAML configuration file. You can find an example YAML configuration file at [Here](https://github.com/cyverse/irodsfs/blob/main/examples/config.yaml). The "resource" field is not used in the example, but you can add the field to specify the resource server.

Let me know if it doesn't work for you.

**Comment by Narushima2030** [comment]
Thank you for your response.
I was able to specify the RESOURCE using methods 1 and 2 you taught me.
