### ISSUE TITLE
Support SSL

### ISSUE THREAD

**Issue by iychoi** [cyverse/irodsfs#3]
Need to support SSL connection.
This is implemented in go-irodsclient, but not connected.

**Comment by ac55-sanger** [comment]
Any update on this? 
Even we are looking in to this and need SSL support. 
Thanks.

**Comment by iychoi** [comment]
> Any update on this?
> Even we are looking in to this and need SSL support.
> Thanks.

I had no time to work on this yet. Probably, I will be able to work on this early in August.
I also need to setup SSL supported iRODS server for testing. (haven't done this before)
Any contribution is welcomed!

**Comment by ac55-sanger** [comment]
@iychoi
https://github.com/cyverse/irodsfs/pull/7

I tested it and it works great for our PAM authentication (with SSL) environment.

**Comment by iychoi** [comment]
@ac55-sanger Thanks for the test.
Can you share how you setup the client and server for the test? Can you describe it in a markdown file and make a merge request to add it in this repo? It will be helpful for others I think.

**Comment by iychoi** [comment]
Oh. I just realized that you made MR already. Thanks for it :-)
