### ISSUE TITLE
Tell me about core.re rulebase calls in irodsfs

### ISSUE THREAD

**Issue by Narushima2030** [cyverse/irodsfs#35]
Hi, I want to set the same rules as the iput and iget commands when moving files with irodsfs.

There is an event handler in core.re.

When extracting files from a mounted local directory,
pep_api_data_obj_get_pre, pep_api_data_obj_get_post are not executed.

When adding files to a mounted local directory
You can see pep_api_data_obj_put_post or acPostProcForPut running.
Also, if you download with the iget command,
I have verified that pep_api_data_obj_get_pre and pep_api_data_obj_get_post are running.

If I want to get a file from a mounted local directory
Please let me know if there is a way to do pep_api_data_obj_get_pre, pep_api_data_obj_get_post.

**Comment by iychoi** [comment]
Hi,

irodsfs (iRODS FUSE Lite) does not use the same APIs as iCommands (iget and iput). irodsfs uses streaming APIs so it doesn't trigger the same PEPs. 

You will need to take a look following PEPs.
- pep_api_data_obj_create_pre and pep_api_data_obj_create_post (for Writing a new file)
- pep_api_data_obj_close_pre and pep_api_data_obj_close_post (for Reading and Writing)
- pep_api_data_obj_open_pre and pep_api_data_obj_open_post (for Reading and Writing)

Quick idea to detect the read (get) and write (put) is like this.
- Check pep_api_data_obj_open_post and its file open flag to see if it is opened with RO/WO/RW.
- When pep_api_data_obj_close_post is called, decide if it is read or write based on the file open flag.

I haven't played this. So there's no actual working code other than this comment. Hope this helps.

**Comment by Narushima2030** [comment]
Hi, 

thanks for your reply.
Thanks for letting me know, especially about the file open flag.
I will try to deal with it the way you taught me.

If you don't mind, I would appreciate it if you could tell me one more thing.
I am using irodsfs. The "resource" to be used is specified by specifying "resource" in the configuration file or by specifying the -R option of the command when mounting.
I want to get the "resource" specified in irodsfs with PEP.
is there a way to get it?

**Comment by iychoi** [comment]
I believe there is a way to get it. But I'm not good at iRODS Rules. I think you will get better answer about iRODS Rules / PEPs from iRODS Google Group.

https://groups.google.com/u/1/g/irod-chat

**Comment by Narushima2030** [comment]
thank you very much.
I got it. I'll ask on irod-chat.
