### ISSUE TITLE
Can irodsfs work with samba or nfs mounted directories?

### ISSUE THREAD

**Issue by Narushima2030** [cyverse/irodsfs#36]
When using a samba or nfs mounted directory as a mount point for irodsfs, irodsfs does not work due to network errors.
Am I correct in understanding that irodsfs cannot be mounted on a mounted directory?
Is there a way to make it work with settings or something?
```
nfs mount /mnt/nfs_share
$ mount
10.1.19.141:/mnt/nfs_share on /local/home/ubuntu/testfs type nfs4

Configure irodsfs with /mnt/nfs_share as the mount point.
$ ./irodsfs/bin/irodsfs --config ./irodsfs/config.yaml /mnt/nfs_share/
```

**Comment by iychoi** [comment]
I don't understand what you want to do. Why do you want to mount irodsfs over NFS mounted directory? Is it to access irods or nfs?
Mounting a filesystem client on a directory that is already mounted is a violation. This restriction is made by OS level, not the irodsfs.

**Comment by Narushima2030** [comment]
Thank you very much for your reply.
I wanted to see if irodsfs could be used to manage irods data on an already used nfs mounted directory.
Thank you for letting me know that I didn't understand that it was prohibited at the OS level.

**Comment by Narushima2030** [comment]
Sorry, I'm a little confused. Is the following understanding correct?
You may have heard the same thing, but let me confirm.
・I want to access irodsfs from the client using smb/nfs etc. in the following way, but I can't.
A) Mount irods-fs to directory <B> on your server.
B) Export directory <B> with samba/nfs
C) Mount the samba/nfs exported directory <A> on the client.

```
┌─────────────┐        ┌────────────┐        ┌────────────────┐
│  client     │        │  server    │        │ irods          │  
│    ┌────┐   │        │   ┌────┐   │        │        ┌─────┐ │
│    │dirA│── nfs mount ──>│dirB│── iros fuse mount──>│collC│ │
│    └────┘   │        │   └────┘   │        │        └─────┘ │
│             │        │ nfs exports│        │                │
└─────────────┘        └────────────┘        └────────────────┘ 
           mount -t nfs dirB dirA　 irodsfs --config config.yaml dirB
```

**Comment by iychoi** [comment]
I have not tried such configuration. But I found that it does not work with NFS v3. Try using v4 and configurations.

https://unix.stackexchange.com/questions/102617/having-trouble-exporting-fuse-via-nfs

**Comment by Narushima2030** [comment]
thank you for your reply.
Very helpful.
I was checking with nfs v4.
I'll research the nfsrods you advised and consider using them.
