### ISSUE TITLE
irods version and irodsfs version problem

### ISSUE THREAD

**Issue by peggy0135** [cyverse/irodsfs#38]
hi @iychoi 
I am using irods 4.3.1 and trying to use irodsfs v0.7.8.
But it doesn't work. So I try irodsfs v0.9.4 and it works.
So is there anything like irods server version <----> irodsfs version which can be referenced?
Thank you

**Comment by iychoi** [comment]
Hi @peggy0135 
Is there any reason you want to use the old version of irodsfs? 
irodsfs v0.7.8 had bugs that are fixed in v4.3.1, so I recommend using the latest version. Especially, PAM/SSL authentication was not well implemented in the old version.
There's no irods server <-> irodsfs version guideline. It is actually not required, as irodsfs implements standard irods protocol and irods server is backward compatible. The newer version is generally more stable.

**Comment by peggy0135** [comment]
hi @iychoi ,  
I am facing another problem with the latest version.
situation: I am ok with root user but when I used other user.
It told me that it can't start child process.
`[chao@irods01 irodsfs]$ ./bin/irodsfs -f -c ~/.irods/irods_config.yaml ~/irodsfs_testmnt
time="2024-01-17 15:20:38.074650" level=info msg="Logging to \"/home/chao/irodsfs/cmjnvhkpk5eu87rob4gg.log.parent\"" function=ProcessCommonFlags package=commons
time="2024-01-17 15:20:38.082497" level=info msg="Found FUSE Device. Starting iRODS FUSE Lite." function=parentMain package=main
time="2024-01-17 15:20:38.082575" level=info msg="iRODS FUSE Lite version \"v0.9.4\", commit \"d585fbf5874679293ee3764c84d445894d8fd16c\"" function=run package=main
time="2024-01-17 15:20:38.082627" level=info msg="Connect to IRODS server using \"native\" auth scheme" function=NewFileSystem package=irodsfs
time="2024-01-17 15:20:38.082678" level=info msg="Initializing an iRODS file system client" function=NewFileSystem package=irodsfs
time="2024-01-17 15:20:38.082765" level=info msg="Initializing an iRODS native file system client" function=NewFileSystem package=irodsfs
time="2024-01-17 15:20:38.082868" level=info msg="Initializing virtual path mappings" function=NewFileSystem package=irodsfs
time="2024-01-17 15:20:38.082905" level=info msg="Building a hierarchy" function=NewVPathManager package=vpath
time="2024-01-17 15:20:38.082937" level=info msg="Building a VPath Entry - /QCTZone/home/chao" function=buildOne package=vpath struct=VPathManager
time="2024-01-17 15:20:38.170940" level=error msg="failed to login to irods:\n    github.com/cyverse/go-irodsclient/irods/connection.(*IRODSConnection).Connect\n        /home/chao/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.12.19/irods/connection/connection.go:253\n  - failed to receive authentication challenge message body (failed to receive a response message: failed to read header size: failed to receive data: failed to read from socket: read tcp 192.168.100.45:55284->192.168.100.45:1247: read: connection reset by peer):\n    github.com/cyverse/go-irodsclient/irods/connection.(*IRODSConnection).login\n        /home/chao/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.12.19/irods/connection/connection.go:451\n  - authentication error (auth scheme: 'native', username: 'chao', zone: 'QCTZone')" function=Connect package=connection struct=IRODSConnection
time="2024-01-17 15:20:38.171249" level=error msg="failed to check path - /QCTZone/home/chao" error="failed to connect to irods server: failed to login to irods: failed to receive authentication challenge message body (failed to receive a response message: failed to read header size: failed to receive data: failed to read from socket: read tcp 192.168.100.45:55284->192.168.100.45:1247: read: connection reset by peer): authentication error (auth scheme: 'native', username: 'chao', zone: 'QCTZone')" function=buildOne package=vpath struct=VPathManager
time="2024-01-17 15:20:38.171450" level=info msg="Initializing File Handle Map" function=NewFileSystem package=irodsfs
time="2024-01-17 15:20:38.171668" level=error msg="failed to list groups for a user \"chao\":\n    github.com/cyverse/irodsfs/irodsfs.NewFileSystem\n        /home/chao/irodsfs/irodsfs/fs.go:243\n  - failed to get a connection from the pool because pending error is found:\n    github.com/cyverse/go-irodsclient/irods/session.(*IRODSSession).AcquireConnection\n        /home/chao/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.12.19/irods/session/session.go:225\n  - failed to connect to irods server:\n    github.com/cyverse/go-irodsclient/irods/session.(*ConnectionPool).Get\n        /home/chao/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.12.19/irods/session/pool.go:202\n  - failed to login to irods:\n    github.com/cyverse/go-irodsclient/irods/connection.(*IRODSConnection).Connect\n        /home/chao/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.12.19/irods/connection/connection.go:253\n  - failed to receive authentication challenge message body (failed to receive a response message: failed to read header size: failed to receive data: failed to read from socket: read tcp 192.168.100.45:55284->192.168.100.45:1247: read: connection reset by peer):\n    github.com/cyverse/go-irodsclient/irods/connection.(*IRODSConnection).login\n        /home/chao/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.12.19/irods/connection/connection.go:451\n  - authentication error (auth scheme: 'native', username: 'chao', zone: 'QCTZone')" function=NewFileSystem package=irodsfs
time="2024-01-17 15:20:38.171945" level=error msg="failed to create the filesystem:\n    main.run\n        /home/chao/irodsfs/cmd/main.go:226\n  - failed to list groups for a user \"chao\":\n    github.com/cyverse/irodsfs/irodsfs.NewFileSystem\n        /home/chao/irodsfs/irodsfs/fs.go:243\n  - failed to get a connection from the pool because pending error is found:\n    github.com/cyverse/go-irodsclient/irods/session.(*IRODSSession).AcquireConnection\n        /home/chao/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.12.19/irods/session/session.go:225\n  - failed to connect to irods server:\n    github.com/cyverse/go-irodsclient/irods/session.(*ConnectionPool).Get\n        /home/chao/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.12.19/irods/session/pool.go:202\n  - failed to login to irods:\n    github.com/cyverse/go-irodsclient/irods/connection.(*IRODSConnection).Connect\n        /home/chao/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.12.19/irods/connection/connection.go:253\n  - failed to receive authentication challenge message body (failed to receive a response message: failed to read header size: failed to receive data: failed to read from socket: read tcp 192.168.100.45:55284->192.168.100.45:1247: read: connection reset by peer):\n    github.com/cyverse/go-irodsclient/irods/connection.(*IRODSConnection).login\n        /home/chao/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.12.19/irods/connection/connection.go:451\n  - authentication error (auth scheme: 'native', username: 'chao', zone: 'QCTZone')" function=run package=main
time="2024-01-17 15:20:38.172205" level=error msg="failed to run iRODS FUSE Lite:\n    main.parentMain\n        /home/chao/irodsfs/cmd/main.go:139\n  - failed to create the filesystem:\n    main.run\n        /home/chao/irodsfs/cmd/main.go:226\n  - failed to list groups for a user \"chao\":\n    github.com/cyverse/irodsfs/irodsfs.NewFileSystem\n        /home/chao/irodsfs/irodsfs/fs.go:243\n  - failed to get a connection from the pool because pending error is found:\n    github.com/cyverse/go-irodsclient/irods/session.(*IRODSSession).AcquireConnection\n        /home/chao/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.12.19/irods/session/session.go:225\n  - failed to connect to irods server:\n    github.com/cyverse/go-irodsclient/irods/session.(*ConnectionPool).Get\n        /home/chao/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.12.19/irods/session/pool.go:202\n  - failed to login to irods:\n    github.com/cyverse/go-irodsclient/irods/connection.(*IRODSConnection).Connect\n        /home/chao/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.12.19/irods/connection/connection.go:253\n  - failed to receive authentication challenge message body (failed to receive a response message: failed to read header size: failed to receive data: failed to read from socket: read tcp 192.168.100.45:55284->192.168.100.45:1247: read: connection reset by peer):\n    github.com/cyverse/go-irodsclient/irods/connection.(*IRODSConnection).login\n        /home/chao/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.12.19/irods/connection/connection.go:451\n  - authentication error (auth scheme: 'native', username: 'chao', zone: 'QCTZone')" function=parentMain package=main
[chao@irods01 irodsfs]$ `

 Is there anything I can figure out what happen?
Thank you

**Comment by peggy0135** [comment]
Yes, but I can use the same way with root.
So in the config file what can I do?
Thank you

**Comment by peggy0135** [comment]
For the SSL, I set my irods server using pam with ssl.
So what can I do with the irodfs` config.yaml file?
Thank you

**Comment by iychoi** [comment]
I believe your iRODS server is configured to allows root can login via native authentication.

To enable SSL/PAM authentication, checkout following example configuration.

https://github.com/cyverse/irodsfs/blob/main/examples/pam_config.yml

You will need to obtain SSL CA Cert file and other SSL related configuration values (key size, algorithm, salt size, and hash rounds) from your iRODS server administrator. The configuration values are configured during iRODS installation.

Hope this helps.

**Comment by peggy0135** [comment]
my config yaml file is configured according to the pam_config.yml
but when I tried the icommand with PAM is ok.
So I am wondering that is there any problem in my "/etc/pam.d/irods"?
`auth        sufficient    pam_ldap.so
auth        sufficient    pam_permit.so
auth        sufficient    pam_env.so
auth        sufficient    pam_unix.so
auth        sufficient    pam_succeed_if.so
auth        sufficient    pam_deny.so`

or I should created another config file in /etc/pam.d?

Thank you

**Comment by iychoi** [comment]
There's nothing to change to make irods work with irodsfs if it already works with icommands.
irodsfs can also read icommands environment file if no configuration file is given. (without -c). Can you try it and share the log if it doesn't work?

**Comment by peggy0135** [comment]
Finally, it seems my type error in the config file. And it works now. Thank you.

**Comment by iychoi** [comment]
Glad that you found the fix.
