### ISSUE TITLE
Question about PAM Authentication (specifically password) with config yaml files and or irods_environment.json

### ISSUE THREAD

**Issue by jnimoth** [cyverse/irodsfs#41]
Hi Illyoung,
I have a short question about using irodsfs v10.0.2 with either a config.yaml and or a irods_environment.json under `~/.irods`:

1. To work with  a config yaml, do I see it correctly that a password **has** to be specified in the config file? I have it somehow in my memory that older versions of irodsfs allowed to leave this empty and then specify in the terminal/prompt? 
2. There is now also the possibility to not use a separate config yaml, but instead the irods_environment.json file. Do I see it correctly that this also only works if there is a .irodsA file created first (for example via `iinit`?). 

![image](https://github.com/user-attachments/assets/9a3e1fea-4baf-464e-b215-78074fa5928a)

I was wondering if this is correctly observed and also the intended behavior. 
Thanks!

**Comment by iychoi** [comment]
If leaving the password field empty doesn't ask you for typing, it's a bug. Sorry for the issue.
Supporing `iinit` and icommands compatible configuration file was my original intention.
I'll soon fix it!

**Comment by iychoi** [comment]
Please check the new release v0.10.3 that fixes the issue.

https://github.com/cyverse/irodsfs/releases/tag/v0.10.3
